name: CMake Build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake (Ubuntu)
        run: sudo apt-get install cmake

      - name: Configure CMake for Ubuntu
        run: cmake -S . -B build

      - name: Build on Ubuntu
        run: cmake --build build --config Release

      - name: Binary dependencies
        run: ldd build/Example_ExtractInfo

      - name: Run one example
        run: build/Example_ExtractInfo Files/Helix.3mf

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake (Windows)
        run: choco install cmake

      - name: Configure CMake for Windows
        run: cmake -G "Visual Studio 16 2019" -S . -B build

      - name: Build on Windows
        run: cmake --build build --config Release

      - name: Binary dependencies
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          dumpbin /dependents build/Release/Example_ExtractInfo.exe

      - name: Run one example
        run: build/Release/Example_ExtractInfo.exe Files/Helix.3mf

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake (macOS)
        run: brew install cmake

      - name: Configure CMake for macOS
        run: cmake -S . -B build

      - name: Build on macOS
        run: cmake --build build --config Release

      - name: Binary dependencies
        run: otool -L build/Example_ExtractInfo

      - name: Run one example
        run: build/Example_ExtractInfo Files/Helix.3mf