name: CMake Build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3.21.3

      - name: Configure CMake for Ubuntu
        run: |
          cmake -S . -B build

      - name: Build on Ubuntu
        run: |
          cmake --build build --config Release

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3.21.3

      - name: Configure CMake for Windows
        run: |
          cmake -S . -B build

      - name: Build on Windows
        run: |
          cmake --build build --config Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3.21.3

      - name: Configure CMake for macOS
        run: |
          cmake -S . -B build

      - name: Build on macOS
        run: |
          cmake --build build --config Release
